### ISSUE TITLE
Investigate client side rendering for OHM.

### ISSUE THREAD

**Issue by muninn** [OpenHistoricalMap/OpenHistoricalMap#1]

**Comment by JaimeLynSchatz** [comment]
To clarify (please forgive if this is obvious to everyone but me), is this investigating methods _for_ rendering the image vectors on the client that don't put undue stress on the servers or for investigating the ultimate visual style of rendering (ie, side-by-side, overlays, etc.) Or both?

**Comment by timwaters** [comment]
Good question Jaimie  - Part of the "investigation" is about Aims, Requirements, Needs - what does the community want, what is possible, what's been done before, what's achievable within a set timescale etc etc.  it's not at all obvious to anyone at all what this could require!

My impression however for this task is that it's about the rendering of data on the client. 

Have a look at KothicJS for a start point, but there's a few other things out there also. The OSM wiki could be a good place to search through.

**Comment by JaimeLynSchatz** [comment]
:+1: Thanks!

I started the other way with my searching and (admist a lot of info) came across Yahoo's patent on a specific method of client-side rendering: https://www.google.com/patents/US7734412

I'll hit the OSM wiki again, though. (I glossed over a lot of the graphics bits in it the first time I dipped my toes in because I was still in "overview" mode :smile:).

**Comment by muninn** [comment]
The intent here was to support a tool that could support multiple rendering styles without overloading the tile renderer with too many tile sets to work with. I had KothicJS in mind when we talked about this, but the tasks it only to investigate; no need to get it working.

**Comment by JaimeLynSchatz** [comment]
This is a little rough, but I wanted to get something out there before I went too far down the rabbit hole :smile:.

After a lot of digging (and some circular searching), I found this paper(http://www.ahahah.eu/data/doc/gisscience2012_gaffuri_draft.pdf) from 2012 which describes four interoperable parts to making client-side vector rendering work for web mapping:
- Ensuring only the "relevant 'data slice'" or Level of Detail (LoD) is served up to the client. Why bog the browser down with a load of vectors which aren't even viewable at the current zoom/view?
- Deciding between vector tiling or spatial indexing (vector tiling is best for our needs, but the detail/type of images needed for the OSM Buildings project might benefit from using spatial indexing.)
- The use of generalization is important to prevent serving up so many vectors that the map is distorted (the author of the paper shows an example of literally discriminating the forest from the trees that makes the point nicely.) www.ahahah.eu/data/doc/gissience2012_gaffuri_draft.pdf, top of page 9)
- Finally, progressive transmission of the vector data requires that an inital push of vectors goes down to the client (so the browser has something to display) and then the rest of the data can be served.

The paper supports the use of OpenCarto(http://www.opencarto.ahahah.eu/), a Java vector mapping library, but the methods described within can be used as filters for searching for Javascript libraries that would be appropriate for our use.

# Full Package Engines

Kothic.js
https://github.com/kothic/kothic-js
Kothic has the whole package in one place. There are lots of rave reviews about other libraries and tools, though:

Cartagen
http://cartagen.org/
Cargagen uses Geographic Style Sheets to describe how to render the vectors. It's wiki specifically says it can be useful for rendering time-based data https://github.com/jywarren/cartagen/wiki

# Notable Libraries

OpenLayers
Many users on gis.stackexchange like the performance of OpenLayers. It uses WebGL, which has some compatability issues, though - http://caniuse.com/webgl

Polymaps
http://polymaps.org/
Javascript library, uses SVG

Leaflet.js
http://leafletjs.com/index.html
Another Javascript library, apparently especially good for mobile, already in use for the Android and iOS Wikimedia apps. 

CartoDB
https://github.com/CartoDB/torque/tree/new_torque
CartoDB uses Leaflet. I'm still looking through it - it's demo page on
http://cartodb.github.io/torque/ is rather striking and uses historical data.

# Additional Thoughts (Ramblings?)

I came across several different methods for how to transmit the vector data (XML, JSON, GeoJSON, etc) as well as a very interesting description of how to use the pixel data in an image. ( Ragi Yaser Buruhum's top answer on http://gis.stackexchange.com/questions/15240/how-to-create-vector-polygons-at-the-same-amazing-speeds-giscloud-is-able-to-ren/15947#15947) In this method, the server sends down an image that appears to be blank, but instead has all of the vector data encoded where the pixel RGB, etc data would be.

**Comment by rwarren2** [comment]
obsolete.
