### ISSUE TITLE
Layers are obsolete.

### ISSUE THREAD

**Issue by rwarren2** [OpenHistoricalMap/OpenHistoricalMap#11]
Layers are obsolete in the app, including in ID which is calling map quest as a background layer.

**Comment by Abbe98** [comment]
OpenHistoricalMap/iD should be working. Once I find the time I will update it to iD 2.0+ too...

**Comment by rwarren2** [comment]
Yes, I am going to take out the 2008/2009 layers. Need to chat with you about restarting an rdf export of OHM.

**Comment by Abbe98** [comment]
Okey.

I got an RDF/turtle API endpoint somewhere, could look into it on Monday. Any specific use cases? :-)

**Comment by rwarren2** [comment]
@Abbe98 discussion moved to #12
