### ISSUE TITLE
reinstall/upgrade Overpass API

### ISSUE THREAD

**Issue by rwelty1889** [OpenHistoricalMap/OpenHistoricalMap#15]

**Comment by p1230** [comment]
Since I have intensified mapping in OHM again, I would appreciate it for the Germersheim project and in general.

**Comment by rwelty1889** [comment]
On 12/26/17 4:04 PM, p1230 wrote:
>
> Since I have intensified mapping in OHM again, I would appreciate it
> for the Germersheim project and in general.
>
i'd been meaning to ask what the prospects are. i have a project that
had it deployed,
it's been broken for quite a while.

i understand that server access is challenging, but i'm prepared to do
the reinstallation (i did do the original overpass installation for OHM).

richard

-- 
rwelty@averillpark.net
 Averill Park Networking - GIS & IT Consulting
 OpenStreetMap - PostgreSQL - Linux
 Java - Web Applications - Search

**Comment by rwarren2** [comment]
Richard, what do you need from me to get it installed?

**Comment by rwarren2** [comment]
Moved to ohm-website/#42
