### ISSUE TITLE
Add additional NLS Map Layer

### ISSUE THREAD

**Issue by a01020304uk** [OpenHistoricalMap/OpenHistoricalMap#18]
As I cannot find a way to contact anyone direct can the following map layer be added to the list of layers

Ordnance Survey six-inch to the mile (1:10,560), 1888-1913
http://nls-1.tileserver.com/fpsUZbULUtp1/{z}/{x}/{y}.jpg

also can you tell me the tileserver link you use for OHM as wish to create a website with bing/google slider maps with OHM as base.

**Comment by rwarren2** [comment]
OHM Tile server is at http://www.openhistoricalmap.org/ohm_tiles/{z}/{x}/{y}.png

Adding layers is currently time consuming. It is on the list of things to do.

**Comment by rwarren2** [comment]
Move this to ohm-website#38.
