### ISSUE TITLE
recent changesets not rendering

### ISSUE THREAD

**Issue by rwelty1889** [OpenHistoricalMap/OpenHistoricalMap#19]
it's been a couple of days since any of my changesets caused the rendering to update. here is an example, an extension of an existing way in the Erie Canal:

https://www.openhistoricalmap.org/way/198662627#map=16/42.8457/-73.9072&layers=OD&date=1900&daterange=1800,2021

**Comment by Rub21** [comment]
@rwelty1889 Thanks for reporting this, we got another similar issue, that I just fixed update process, could you check again the edition  are already there.  Thanks,

On my end it looks like it is showing the edition
![image](https://user-images.githubusercontent.com/1152236/132248902-ddc2607f-5161-4ab4-9e22-cba79f5187c2.png)
