### ISSUE TITLE
Investigate Dynamic Temporal Tile Serving 

### ISSUE THREAD

**Issue by muninn** [OpenHistoricalMap/OpenHistoricalMap#2]
Keep an eye on  http://wiki.nginx.org/ReverseProxyCachingExample

**Comment by timwaters** [comment]
(changed the title to make it wider in scope :smile:  )

Investigate the solutions for serving up dynamic temporal tiles.

Current set up: http://wiki.openstreetmap.org/wiki/OHM/Dev
Requires manual creation of pg views and tweaking cartocss file. 

Tile schemes 
renderd / mod_tile
Look at the osm.de useage  /tile/de/1/2/3.png where de gets used in the query

Reverse proxying of tiles:
Keep an eye on:
Nginx: http://wiki.nginx.org/ReverseProxyCachingExample 
Apache: http://httpd.apache.org/docs/2.2/mod/mod_cache.html
Tilecache / Tilestache / other solutions

Look into any existing solutions in the wild.

---

Wikipage: http://wiki.openstreetmap.org/wiki/OHM/TileServer

**Comment by muninn** [comment]
Early on in the mailling list we had ideas of using

 /tile/HistoricalEra/x/y/z.png or  /tile/End_date/Start_date/x/y/z.png

**Comment by rwarren2** [comment]
obsolete.
