### ISSUE TITLE
Add a time slider to OHM Rails Front End

### ISSUE THREAD

**Issue by ghost** [OpenHistoricalMap/OpenHistoricalMap#3]
When a javascript time slider is created, it must be added to the rails front end.

http://wiki.openstreetmap.org/wiki/Rails_port/UI

**Comment by timwaters** [comment]
It might be suitable to put this in our ohm-website issue tracker https://github.com/OpenHistoricalMap/ohm-website/issues

**Comment by muninn** [comment]
Moved.

**Comment by timwaters** [comment]
A time slider widget can also occur in other places too - in JOSM editor, in iD, in Potlatch, in the data view, in the export functions, on the website front end etc. 

All will probably be written differently for each case.

**Comment by muninn** [comment]
Yes. This microtask is meant as the initial test case, since its what the people see first when they load the page.

**Comment by JaimeLynSchatz** [comment]
I've got a first-first-first draft (a doodle, really...:smile:) 

http://jaimelynschatz.github.io/time_slider_mockup.png

Edited to add: Whoops. Posting this to the proper issue now...
