### ISSUE TITLE
Accept start_year from TimeSlider and Send to Renderer

### ISSUE THREAD

**Issue by JaimeLynSchatz** [OpenHistoricalMap/OpenHistoricalMap#4]
Not sure if this is the proper place for this, but saw the note in IRC about putting more in GitHub Issues, so I'm re-posting my screen shot from my baby-step victory:

![Image of successfully capturing start_year](http://jaimelynschatz.github.io/BabyStepProgress.png)

The image is posted at: http://jaimelynschatz.github.io/BabyStepProgress.png
The code is on the time_slider2 branch here: https://github.com/JaimeLynSchatz/ohm-website/tree/time_slider2

I've been sending the start_year through the search function but need try something else (write a time_search function?) because a lot of international postal codes can match years. (Unless we want to keep that functionality and use it as a [disambiguation page](https://en.wikipedia.org/wiki/The_Book) like on Wikipedia, et al.)

**Comment by JaimeLynSchatz** [comment]
Currently getting a 500 error. Not very helpful. I've pushed my most recent commits up to https://github.com/JaimeLynSchatz/ohm-website/tree/time_slider2

**Comment by JaimeLynSchatz** [comment]
Commenting through email failure. :/
From Gmail:
Rob H Warren
Jun 27 (1 day ago)

to me 
What part is giving you the 500? webserver long error.log should tell you more.
On Jun 27, 2014, at 3:55 AM, JaimeLynSchatz notifications@github.com wrote:

> Currently getting a 500 error. Not very helpful. I've pushed my most recent commits up to https://github.com/JaimeLynSchatz/ohm-website/tree/time_slider2
> 
> —
> Reply to this email directly or view it on GitHub.

Jaime Schatz jaimelynschatz@gmail.com
Jun 27 (1 day ago)

to Rob 
It's surrounding the call to search_start_year. After I wrote this, I had to restart and noticed more helpful errors in the terminal window. Making a little progress. One problem was mixed up naming. I should be able to update soon with some success!

**Comment by JaimeLynSchatz** [comment]
I need to give the map something to deliver for the start_year_search. Working on that now.

**Comment by JaimeLynSchatz** [comment]
@muninn: I've made some progress. What should the search bring up? I modified the standard error message to parrot back the query string.
![image of query result](http://jaimelynschatz.github.io/start_year_query.png)

The code is pushed up on my [time_slider2 branch](https://github.com/JaimeLynSchatz/ohm-website/tree/time_slider2).

**Comment by rwarren2** [comment]
Obsolete.
