### ISSUE TITLE
planet dumps

### ISSUE THREAD

**Issue by timwaters** [OpenHistoricalMap/OpenHistoricalMap#5]
currently minutely replication is enabled

see http://wiki.openstreetmap.org/wiki/OHM/Dev

osmosis uses 0.43

http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.43#--write-xml_.28--wx.29

set up system like planet.osm but for ohm

just regular planet at the moment?

**Comment by jeffreyameyer** [comment]
Tim - ref: minutely, sweet!

What is the regular planet?

One of the current issues with the OHM natural features was that I did a
fairly messy job if filtering out man-made features (which was complicated
by some similarly sloppy mapping in the OSM baseline. It could definitely
use an update / scrub up!
- Jeff

On Friday, January 9, 2015, Tim Waters notifications@github.com wrote:

> currently minutely replication is enabled
> 
> see http://wiki.openstreetmap.org/wiki/OHM/Dev
> 
> osmosis uses 0.43
> 
> http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.43#--write-xml_.28--wx.29
> 
> set up system like planet.osm but for ohm
> 
> just regular planet at the moment?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenHistoricalMap/OpenHistoricalMap/issues/5.

## 

Jeff Meyer
Global World History Atlas
www.gwhat.org
jeff@gwhat.org
206-676-2347

OpenStreetMap: Mapping with a Human Touch
osm: Open Historical Map (OHM)
http://wiki.openstreetmap.org/wiki/Open_Historical_Map / my OSM user page
http://www.openstreetmap.org/user/jeffmeyer
t: @GWHAThistory https://twitter.com/GWHAThistory / @OpenHistMap
f: GWHAThistory https://www.facebook.com/GWHAThistory

**Comment by rwarren2** [comment]
Planet dumps have restarted.

**Comment by rwarren2** [comment]
A week's work of planets are available at dump.openhistoricalmap.org

**Comment by rwarren2** [comment]
Planet and minute replication ongoing without problem.
