### ISSUE TITLE
repository for OHM usage examples

### ISSUE THREAD

**Issue by rwelty1889** [OpenHistoricalMap/OpenHistoricalMap#6]
we talked about this briefly on the mailing list. i'd be happy to post my leaflet/jquery thingy for race track display as an example of displaying OHM data.

**Comment by vlad00777** [comment]
Is it possible to use OHM on external websites via Leaflet/OpenLayers? I can not find any documentation for this. Thx

**Comment by jeffreyameyer** [comment]
@vlad00777 - most definitely, although I'm not sure if we've done this with any attention to the time parameters in the URL.

@rwelty1889 - can you comment here? @gregallensworth?

**Comment by rwelty1889** [comment]
this is a capability we had before the new renderer came online. it is in theory possible but i never got all that far with it. it would require some work on a leaflet extension - which would be worth doing, but right now i'm completely overloaded.

**Comment by rwelty1889** [comment]
what  i've been doing is displaying raster base layers (TMS layers & OSM layers), and then using overpass queries on OSM and OHM to fetch features and overlay them. i would love to be able to have a OHM base layer with a time slider. that is what would require some sort of leaflet extension.
