### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by SomeoneElseOSM** [OpenHistoricalMap/OpenHistoricalMap#7]
http://www.openstreetmap.org/note/610114 describes some data moved from OSM to OHM.  The OHM node created was http://www.openhistoricalmap.org/node/2083425344 , but that doesn't seem to be in the data that has been restored.

**Comment by rwarren2** [comment]
Yes, the data is lost. I'll post to the mail list about this.

**Comment by mmd-osm** [comment]
Hi everyone. I have found an old planet dump on my disk dated 2016/01/23. Will post a link once the upload finishes.

**Comment by rwarren2** [comment]
Excellent. Reloading the data should be interesting. Have to check how many people made edits since we restarted the system.

**Comment by mmd-osm** [comment]
OK, here we go: http://dev.overpass-api.de/tmp/psv/ohm/ohm_planet_20160123.pbf

To reduce file size I have converted the osm.bz2 file to pbf via osmium tool. Please let me know if you see some issues with the file.

**Comment by SomeoneElseOSM** [comment]
Excellent news!  For the benefit of anyone else who might want to download that, how big actually is that?

**Comment by mmd-osm** [comment]
It's 722 MB in total. Not too much compared to the usual osm planet dumps. So, let's grab your copy today!

**Comment by rwarren2** [comment]
Getting "HTTP request sent, awaiting response... 403 Forbidden"

**Comment by mmd-osm** [comment]
Can you try again please? wget was blocked in .htaccess

**Comment by rwarren2** [comment]
Got a copy. Will work on this today +6hours.

Thank you for this.

**Comment by mmd-osm** [comment]
File contents look a bit strange, though. I can only find some nodes, but no ways or relations. The original file was called ohm_planet_20160123.osm.bz2 with a file size of 1343133623. Is that somewhat in line with what you would expect? I will also upload the original file, but that'll take a bit longer...

http://dev.overpass-api.de/tmp/psv/ohm/ohm_planet_20160123.osm.bz2   - 1.3GB

**Comment by rwarren2** [comment]
Downloading this file too. Working on it.

**Comment by rwarren2** [comment]
<relation id="2660914" version="2" timestamp="2016-01-15T17:44:49Z" uid="349" user="p1230" changeset="2005">

I looks like the dump is complete. I am going to need to figure out how to reload this data.

**Comment by rwarren2** [comment]
Thanks for this!

**Comment by mmd-osm** [comment]
It's a bit strange that things like http://www.openhistoricalmap.org/way/198180456 are missing in the dump. It may be that the dump generation last year already had some issue and only exported nodes. In the worst case this dump is not that helpful. I downloaded it last year to run some tests with Overpass and start_dates.

**Comment by mmd-osm** [comment]
It's a bit strange that things like http://www.openhistoricalmap.org/way/198180456 are missing in the dump. It may be that the dump generation already had some issues last year and only exported nodes.

In the worst case this dump is not that helpful as baseline for a full restore, but maybe you could selectively extract some POI nodes at least, or use stale nodes as starting points for new ways (avoids some of the tracing effort).

Maybe you could try and reach out to Jochen (@joto) on how to use osmium tools to filter / merge your 2015 dump and my 2016 dump into something useful.

BTW: I downloaded it last year to run some tests with Overpass and start_dates.

**Comment by rwarren2** [comment]
Ok. At this point, this is obsolete.
