### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Karthoo** [OpenHistoricalMap/OpenHistoricalMap#8]
Hey,
I can't log in since OHM is back online because everytime I try to log in it redirects me to the email confirming page, but I didn't get an email. Can you log in without problems?

**Comment by Abbe98** [comment]
I think this has happened in the past too and there seams like there are a few users who can't login.

**Comment by rwarren2** [comment]
Yet-another-issue with email and firewall. Apologies.

**Comment by rwarren2** [comment]
This should be fixed now.
