### ISSUE TITLE
Tile server still not updating!

### ISSUE THREAD

**Issue by rwarren2** [OpenHistoricalMap/OpenHistoricalMap#9]

**Comment by JDruhanC** [comment]
Hi. I have been doing work on Mobile, AL, during the Civil War. I decided to temporarily halt my work, as none of my edits or additions are rendering, although I can see them all while using the iD editor. Is this an issue that has been resolved, or is it isolated to myself?

**Comment by rwarren2** [comment]
@JDruhanC This should be fixed this week. Working on it. Will update this ticket.

**Comment by rwarren2** [comment]
@JDruhanC  Should be fixed and updating every 5 mins. Can you give it a try? 
"It's working on my end"

**Comment by JDruhanC** [comment]
Thanks, my edits are rendering now, if only at close zoom levels.

**Comment by rwarren2** [comment]
Excellent.

**Comment by rwelty1889** [comment]
On 3/20/17 5:29 PM, rwarren2 wrote:
>
> @JDruhanC <https://github.com/JDruhanC> Should be fixed and updating
> every 5 mins. Can you give it a try?
>
looks good to me. all my recent edits are showing up.

thanks for all the hard work,
   richard

-- 
rwelty@averillpark.net
 Averill Park Networking - GIS & IT Consulting
 OpenStreetMap - PostgreSQL - Linux
 Java - Web Applications - Search
